
-- parameter_name   parameter_mode(IN,OUT)   datatype 
CREATE OR REPLACE PROCEDURE HELLO_PLACE(PLACE_IN IN VARCHAR2) IS
  L_MESSAGE VARCHAR2(100);
BEGIN
  L_MESSAGE := 'Hello ' || PLACE_IN;
  DBMS_OUTPUT.PUT_LINE(L_MESSAGE);
END HELLO_PLACE;

/

BEGIN
HELLO_PLACE('World'); HELLO_PLACE('Universe');
END;

/

CREATE OR REPLACE FUNCTION HELLO_MESSAGE(PLACE_IN IN VARCHAR2) RETURN VARCHAR2 IS
BEGIN
RETURN 'Hello ' || PLACE_IN;
END HELLO_MESSAGE;

/
DECLARE L_MESSAGE VARCHAR2(100);
BEGIN
L_MESSAGE := HELLO_MESSAGE('Universe'); DBMS_OUTPUT.PUT_LINE(L_MESSAGE);

END;
