
CREATE OR REPLACE PACKAGE PCK_MY_COMMON AUTHID DEFINER IS
 TYPE STRING_T IS TABLE OF NVARCHAR2(100);
 
 FUNCTION RONDOM_STRING(COUNT_IN IN INTEGER) RETURN STRING_T;
 
 FUNCTION JUST_NUMBER RETURN NUMBER;
END PCK_MY_COMMON;

/
CREATE OR REPLACE PACKAGE BODY PCK_MY_COMMON AS

FUNCTION RONDOM_STRING(COUNT_IN IN INTEGER)
RETURN STRING_T
IS
  L_STRING STRING_T:=STRING_T ();
BEGIN
  L_STRING.EXTEND(COUNT_IN);
  
  FOR INDX IN 1 .. COUNT_IN
  LOOP
    L_STRING(INDX):=DBMS_RANDOM.STRING('U',10);
  END LOOP;
  
  RETURN L_STRING;
END RONDOM_STRING;  

FUNCTION JUST_NUMBER RETURN NUMBER
IS
BEGIN
  RETURN 1;
END;
  
END PCK_MY_COMMON;

/

DECLARE
V_STRING  PCK_MY_COMMON.STRING_T:=PCK_MY_COMMON.RONDOM_STRING(5);

BEGIN
  FOR INDX IN 1 .. V_STRING.COUNT
  LOOP
    DBMS_OUTPUT.PUT_LINE(V_STRING(INDX));
  END LOOP;
END;

/

 CREATE OR REPLACE TYPE STRING_T IS TABLE OF NVARCHAR2(100);
 
 /
 
 CREATE OR REPLACE FUNCTION RONDOM_STRING(COUNT_IN IN INTEGER)
RETURN STRING_T
IS
  L_STRING STRING_T:=STRING_T ();
BEGIN
  L_STRING.EXTEND(COUNT_IN);
  
  FOR INDX IN 1 .. COUNT_IN
  LOOP
    L_STRING(INDX):=DBMS_RANDOM.STRING('U',10);
  END LOOP;
  
  RETURN L_STRING;
END RONDOM_STRING;  

/
SELECT COLUMN_VALUE MY_STRING FROM TABLE(RONDOM_STRING(5));
SELECT PCK_MY_COMMON.JUST_NUMBER FROM DUAL;

--NOT WORK because STRING_T not in pipel?ne ?t must be schema level like up select statement
--SELECT COLUMN_VALUE MY_STRING FROM TABLE(PCK_MY_COMMON.RONDOM_STRING(5));
/

BEGIN
  FOR REC IN(SELECT COLUMN_VALUE MY_STRING FROM TABLE(RONDOM_STRING(5)))
  LOOP
    DBMS_OUTPUT.PUT_LINE(REC.MY_STRING);
  END LOOP;
END;