/*CREATE TABLE ANIMALS
(
  NAME VARCHAR2(10),
  SPECIES VARCHAR2(20),
  DATE_OF_BIRTH DATE
);*/

-- NOT WORKING
--CREATE TYPE ANIMALS_NT IS TABLE OF ANIMALS%ROWTYPE;


CREATE OR REPLACE TYPE ANIMALS_OT IS OBJECT
(
 NAME VARCHAR2(10),
  SPECIES VARCHAR2(20),
  DATE_OF_BIRTH DATE
);

/
CREATE OR REPLACE TYPE ANIMALS_NT IS TABLE OF ANIMALS_OT;

/

CREATE OR REPLACE FUNCTION ANIMALS_FAMILY(DAD_IN IN ANIMALS_OT,MOM_IN IN ANIMALS_OT)
RETURN ANIMALS_NT
IS
  L_FAMILY ANIMALS_NT:= ANIMALS_NT(DAD_IN,MOM_IN);
BEGIN
  FOR INDX IN 1 .. CASE MOM_IN.SPECIES
                    WHEN 'RABBIT' THEN 12
                    WHEN 'DOG' THEN 4
                    WHEN 'KANGARDO' THEN 1
                    END
    LOOP
      L_FAMILY.EXTEND;
      L_FAMILY(L_FAMILY.LAST):=ANIMALS_OT('BABY' || INDX,MOM_IN.SPECIES,ADD_MONTHS(SYSDATE,-1 * DBMS_RANDOM.VALUE(1,6)));
    END LOOP;
    
    RETURN L_FAMILY;

END ANIMALS_FAMILY;


/

SELECT *
FROM TABLE(ANIMALS_FAMILY(ANIMALS_OT('HAPPY','RABBIT',SYSDATE-500),ANIMALS_OT('HIPY','RABBIT',SYSDATE-300)));